### ISSUE TITLE
It keeps updating the Game Gear core even though it's already been updated to the newest version

### ISSUE THREAD

**Issue by naveedster** [RetroDriven/Pocket_Updater#18]
It keeps updating the Game Gear core even though it's already been updated to the newest version.

Also, can you make it tell you at the end what things it updated, so you dont need to scroll through all the skipped updates?

**Comment by RetroDriven** [comment]
I created a Pull Request for Spiritualized1997 to fix this as well as update the Version so the Updater doesn't keep pulling that down.

**Comment by RetroDriven** [comment]
This issue has been resolved in v1.3.3
