### ISSUE TITLE
Cannot download, windows 11 says it’s a virus

### ISSUE THREAD

**Issue by naveedster** [RetroDriven/Pocket_Updater#25]
I can’t download because windows 11 says it’s a virus

**Comment by scyto** [comment]
no issues here, on latest insider, it does invoke smartscreen as it is not signed, but that can be skipped

**Comment by RetroDriven** [comment]
I paid for a Code Signing Cert so the EXE is signed now. It's not the more expensive one that auto approves/skips Windows Smart Screen but I'm hoping this will help.
