### ISSUE TITLE
Spamming updates

### ISSUE THREAD

**Issue by ifighftdragons** [RetroDriven/Pocket_Updater#30]
Not an issue with the core per se.

But it's not okay subscribing/watching for updates, when you get spammed about 15 times in a row for test updates.

Just thought I'd log the issue, so you'd notice it.
Currently unsubbed because of constant spam updates. Will re-sub once this is fixed.

**Comment by RetroDriven** [comment]
Noted... I'll create a private Repo to test with going forward.
