### ISSUE TITLE
Old firmwares must be removed for install to take place

### ISSUE THREAD

**Issue by pusscat** [RetroDriven/Pocket_Updater#31]
Updater auto-grabs the latest firmware and places it on the external drive, however when multiple firmwares are present in the root, updates dont take place.

I propose an oldFirmwares directory, into which all .bin files in the root directory are moved when a new firmware is found.

**Comment by Compeau** [comment]
Pocket_Updater/lib/Updater/Updater.cs:458 seems to be deleting the old firmware file after downloading the new one.  Did you have multiple old firmware files sitting in your root before ever running the updater?  Or is that not deleting the old firmware file as intended?

**Comment by RetroDriven** [comment]
This issue should be resolved now. If there are any issues going forward just let me know.
