### ISSUE TITLE
Manage Cores section: save button banner hiding the bottom line (or maybe lines? I can t see so I can't tell how many lines are hidden) of the cores list

### ISSUE THREAD

**Issue by StardustX7** [RetroDriven/Pocket_Updater#40]
1.3.9 windows 10 1080p resolution

thanks for this great software, it's a blessing

**Comment by RetroDriven** [comment]
Can you upload a screenshot of this please? Does it look the same when you Maximize the Window?

**Comment by StardustX7** [comment]
Yes it's the same when the window is maximized, here are the screenshots
normal size [https://i.postimg.cc/N0KF9zjn/2023-01-03.png](url)
maximized [https://i.postimg.cc/5ysWmfPS/2023-01-03-1.png](url)
Thank you

**Comment by StardustX7** [comment]
> Can you upload a screenshot of this please? Does it look the same when you Maximize the Window?

Yes it's the same when the window is maximized, here are the screenshots
normal size [https://postimg.cc/NywBZbT8/94a046ba](url)
maximized [https://postimg.cc/vxxKYww4/0b82014e](url)
Thank you

**Comment by RetroDriven** [comment]
Thanks! How do things look with v1.4.1?

**Comment by StardustX7** [comment]
> Thanks! How do things look with v1.4.1?

The manage cores menu looks perfectl now in 1.4.1, the issue is fixed thanks for your hard work.

I also noticed that Sorcer Striker and Kingdom Grandprix cores from pram0d are not listed in the manage cores menu, but they are downloaded and installed by the application, and as the others toaplan 2 cores from pram0d are all listed separately in the menu, I don't know if it's intentional or not, maybe it's just linked with the common ressources you use with the command line updater, so I just report it here in the case it can be useful, but it's absolutely not a breaking issue that needs to be fixed, just consider this as a note for consistency of the core listing.

Thanks again for all what you do.
