### ISSUE TITLE
Version 1.4 New version

### ISSUE THREAD

**Issue by SwiftArsonist** [RetroDriven/Pocket_Updater#42]
Downloaded the new version and still keeps saying there is a new version. Redownloaded and still the same issue.

**Comment by PapiFed** [comment]
Same issue here.

**Comment by FourEyedGeek** [comment]
Ditto.

**Comment by RetroDriven** [comment]
I have to make a quick v1.4.0 to fix this since it didn't like just v.1.4 for whatever reason.
