### ISSUE TITLE
Error downloading CPS1

### ISSUE THREAD

**Issue by toaks2804** [RetroDriven/Pocket_Updater#44]
Getting an error on CPS core. I am a Patreon Supporter as well.

Uh oh something went wrong.
'0x00' is an invalid start of value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
Restoring platforms folder

**Comment by matthutchinson** [comment]
Me too

**Comment by RetroDriven** [comment]
This should be resolved with the latest v1.4.1 Release.
