### ISSUE TITLE
Error: No Internet Connection Detected

### ISSUE THREAD

**Issue by RobitGames** [RetroDriven/Pocket_Updater#48]
Full error upon booting Pocket Updater: No Internet Connection Detected. Failed to check for App Updates.

Subsequently when I click on "Manage Cores" I get this error: No Internet Connection Detected

The app was working fine in an older version. After updating to version 1.4.3 this error pops up. I added the EXE to my virus software's white list and ran as an administrator.

**Comment by RobitGames** [comment]
It seems to have been a conflict with a Linux filesystem app I was running. Updater is running as intended now.

**Comment by RaikaZelkova** [comment]
I was also having this issue but i'm not sure what is causing the conflict. I'm on W10.
