### ISSUE TITLE
Instance JSON builder for PC Engine CD Core doesn't work recursively

### ISSUE THREAD

**Issue by mathieulh** [RetroDriven/Pocket_Updater#52]
Instance JSON builder for PC Engine CD Core doesn't work recursively, for instance I have my fullset built as this: 

D:\Assets\pcecd\common\TGCD\<game name>
D:\Assets\pcecd\common\PCECD-Translations\<game name>
D:\Assets\pcecd\common\PCECD\<game name>
and so on. 

The JSON builder only seems to only detect if a game is located in a folder inside the common folder, it can't go further recursively.

**Comment by mattpannella** [comment]
correct. it doesn't support this currently. I'll be working on it soon though probably

**Comment by RetroDriven** [comment]
This should be fixed in v1.4.6.2

If there are any issues going forward just let me know.
