### ISSUE TITLE
Selecting Removable Storage -> Update results in drive not found

### ISSUE THREAD

**Issue by DeerSteak** [RetroDriven/Pocket_Updater#54]
If you select Removable Storage, it selects the first removable drive on the system. If that happens to be your SD card and you press Update, you'll get a "The Drive Letter Was Not Found!" message. Press update again and it updates as expected. 

![image](https://user-images.githubusercontent.com/991752/220908076-034bf877-b99f-42fa-9a8a-2232f880fffd.png)

![image](https://user-images.githubusercontent.com/991752/220907830-daa31b7a-3c34-4a85-924c-a859d66240a8.png)

**Comment by RetroDriven** [comment]
I'll do some testing and fix it. The GitHib Token box and Save buttons look off for you as well. Those should be directly below the Use GitHub Token setting.

**Comment by RetroDriven** [comment]
I found/fixed the issue and I'll put that fix in place for the next release.

**Comment by DeerSteak** [comment]
That's awesome, thanks. BTW don't worry about the arrangement too much, I'm using 175% scaling on a 28" 4K monitor, so I'm used to stuff not looking exactly right.

**Comment by RetroDriven** [comment]
You're welcome.
