### ISSUE TITLE
Check boxes for individual cores not appearing under “Manage Cores”

### ISSUE THREAD

**Issue by Gorgonner** [RetroDriven/Pocket_Updater#55]
Check boxes for individual cores not appearing under “Manage Cores”. Unable to select cores.

only check box is the one for all in the blue header

occurring in 1.5.0 and 1.5.1

surface pro 7 
Win 10
i5 16gb ram

**Comment by Gorgonner** [comment]
![Uploading BBA1C72E-348D-447F-A05C-4AC9120DB6D0.jpeg…]()

**Comment by RetroDriven** [comment]
Can you upload a screenshot of what you're seeing?

**Comment by Gorgonner** [comment]
![462B00D1-F5DD-4CF4-AB3A-16643529E102](https://user-images.githubusercontent.com/126216033/221095666-a048d7ec-5c11-4460-9570-0b8f140b1ca3.jpeg)

**Comment by RetroDriven** [comment]
Definitely an odd one. Can you see if the issue remains in v1.5.2?

**Comment by dgarra** [comment]
Can confirm still problematic in 1.5.2.

**Comment by RetroDriven** [comment]
It definitely sounds like a scaling thing. Can you both share what Resolution and DPI/Scaling you have set?

**Comment by Gorgonner** [comment]
1.5.2

Using the surface pro 7 default/“recommended” resolution and scaling:
2736 x 1824
Scale: 200%

Still present on 1.52 with the above resolution and scaling.

The check boxes do appear when I set scaling to 100% (but everything on my screen is then very tiny)

**Comment by dgarra** [comment]
I'm running mine out of a virtual machine, so the scaling is dynamic via the size of the VMware window. If i bring the window to a 1920x1080 display, where the scaling is 100%, the checkboxes show up. Anything larger, like my main 5k display, where the scaling goes above 200%, the gui shows the behavior.

**Comment by RetroDriven** [comment]
Hi - I'm hoping this has all been resolved in v1.5.4

Please check and let me know when possible please.

**Comment by Gorgonner** [comment]
Fix verified on 1.5.4

Thanks for the fix, now I can continue to use my favorite updater 🙂

**Comment by RetroDriven** [comment]
Yay! ☺️

**Comment by dgarra** [comment]
Confirmed resolved in 1.5.4. Thanks and great work on this.
