### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by SWEiNSANE** [RetroDriven/Pocket_Updater#58]
I'm running Windows 11 and since I started using this excellent app, scaling issues have been there. My laptops resolution is 3840 x 2400 pixels and therefore I'm running 225% zoom (scaling).

The issues makes:

- the checkboxes when managing the cores to disappear
- buttons for minimize, maximise and close are really small
- texts are looking wierd and not shown correctly
- can't change the size of the window by dragging the corners
- can't choose drive letter for organizing cores
- update status are not shown when updating pocket when I'm not running the app in full screen mode

**Crippled user interface**
![image](https://user-images.githubusercontent.com/28483297/221438103-b10278e6-e87c-4811-8bfe-81100d398aa9.png)

**No checkboxes when managing cores**
![image](https://user-images.githubusercontent.com/28483297/221438133-b96af47c-020a-45b9-9473-36ab55615be3.png)

**Cannot organize cores**
![image](https://user-images.githubusercontent.com/28483297/221438596-4b669ff3-9cdd-4f70-84f7-2538840a226a.png)

**Comment by RetroDriven** [comment]
Hi - I'm hoping this has all been resolved in v1.5.4

Please check and let me know when possible please.

**Comment by SWEiNSANE** [comment]
Hi,

Sounds great and thanks for an excellent app

**Comment by SWEiNSANE** [comment]
I've now tried v1.5.4 and now everything works as expected - thanks and keep up the good work!

**Update Pocket**
![image](https://user-images.githubusercontent.com/28483297/221658947-8c9d1fac-a6c5-431d-b672-33ca5330397a.png)

**Manage Cores**
![image](https://user-images.githubusercontent.com/28483297/221659044-fb08a32c-bc17-47fe-a1ed-d5bdce3d5221.png)

**Comment by RetroDriven** [comment]
Good deal! You're welcome.
