### ISSUE TITLE
BUG: Timeout while actively downloading files.

### ISSUE THREAD

**Issue by dot-bob** [RetroDriven/Pocket_Updater#63]
I have been getting the error "The request was canceled due to the configured HttpClient.Timeout of 100" while it is actively downloading data.

I can verify the download is active as the task manager shows Pocket Updater is using 1-4Mbps of network traffic.  It requires me to run the updater over and over again until I get a data rate that can complete the download before timing out.

**Comment by TheMrChao** [comment]
+1

...seems to happen with many Jotego cores while scanning external media.

Unable to read E:\Assets\jtvigil\jotego.jtvigil\Vigilante (US, Rev G).json
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

**Comment by uberyoji** [comment]
I think this is because the roms for cps2 are much bigger and since they seem to come from archive.org (which is slow sometimes), they take more than 100s to download and timeout...

**Comment by RetroDriven** [comment]
Some major changes were made in v1.5.6 with Downloads/Speeds. Is this issue still happening?

**Comment by uberyoji** [comment]
Looks fixed on my end. Blazing fast now.
Thanks!

**Comment by RetroDriven** [comment]
Excellent!
