### ISSUE TITLE
Unable to open URLs in "Asset Image Packs" tab without selecting a download location

### ISSUE THREAD

**Issue by demize** [RetroDriven/Pocket_Updater#75]
When first opening the Asset Image Packs tab, no download location is selected. Trying to open any of the Github URLs for the asset packs with no download location selected results in an unhandled (I believe null pointer; not sure) exception until you select a download location.

**Comment by UScr00ge** [comment]
I'm getting the same issue when hitting the download button for any of the asset image packs.

Error details below:
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pocket_Updater.Controls.Image_Packs.Image_Packs.Save_Preferences_Json()
   at Pocket_Updater.Controls.Image_Packs.Image_Packs.dataGridView1_CellContentClick(Object sender, DataGridViewCellEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

```

**Comment by RetroDriven** [comment]
Is this issue still happening with v1.6.1?

**Comment by JackWitherell** [comment]
Still no good: 

![image](https://github.com/user-attachments/assets/8e5dc51b-3fbf-4f56-8552-1a8645c768eb)
