### ISSUE TITLE
[QOL Request] A way to auto-patch/override the Game Gear core's aspect ratio

### ISSUE THREAD

**Issue by HeyItsLollie** [RetroDriven/Pocket_Updater#8]
Quality-of-life request:
Spiritualized1997's Game Gear core has had [the wrong aspect ratio](https://github.com/spiritualized1997/openFPGA-GG/issues/1) set by default since its initial release. Currently, the only fix is to manually edit "video.json" so that the 160x144 resolution has an aspect ratio of 4:3, but manual edits get reverted after an update.

I'd like to suggest one of two possible features to fix this:
1. An option to auto-patch the Game Gear core's aspect ratio, at least until Spiritualized1997 fixes this upstream. Or;
2. A user-maintained "Override" folder, applied after updates have been downloaded. eg: for users who decide to change the SNES core's default aspect ratio, or for retaining [custom core banners](https://www.reddit.com/r/AnaloguePocket/comments/xip3eb/pocket_custom_core_art_v20_snes_update_links_in/) after an update.

**Comment by RetroDriven** [comment]
I just created a Pull Request for Spiritualized1997 to fix this as well as update the Version so the Updater doesn't keep pulling that down.
