### ISSUE TITLE
Unchecked Cores Being Downloaded

### ISSUE THREAD

**Issue by HaydenCupcake** [RetroDriven/Pocket_Updater#80]
Hi,

Pocket Updater v1.6.0 seems to be downloading cores that are not checked. Please see the attached log and screenshot. For example, Pokemon Mini is unchecked but Pocket Updater still downloads it. I don't recall the previous version having this issue.
[pocket_update_log_122123.txt]

(https://github.com/RetroDriven/Pocket_Updater/files/13746589/pocket_update_log_122123.txt)

![Screenshot 2023-12-21 141727](https://github.com/RetroDriven/Pocket_Updater/assets/150538689/9f4963d2-4312-4559-b77b-208fc4da639d)
![Screenshot 2023-12-21 141833](https://github.com/RetroDriven/Pocket_Updater/assets/150538689/fa22a689-e7de-492b-b643-2385fcbe3210)
![Screenshot 2023-12-21 141923](https://github.com/RetroDriven/Pocket_Updater/assets/150538689/8424af46-647b-49d4-9d8a-eb2be98cc880)
![Screenshot 2023-12-21 142010](https://github.com/RetroDriven/Pocket_Updater/assets/150538689/76f1d2d5-c0d2-40ca-899a-ebc2434b97a7)

**Comment by mario-64** [comment]
I can confirm this issue.

**Comment by Fableton** [comment]
Same

**Comment by wadefree85** [comment]
also encountered this issue.  I only use a few cores and would like to only select the ones that I use

**Comment by preppietechie** [comment]
Confirmed... I now have a ton of cores I don't use installed. Is there a way to uninstall them?

**Comment by uberyoji** [comment]
Same problem. @preppietechie I use Pocket Sync to remove those individually.

**Comment by Arq24** [comment]
Same 
App is basically usless
And looks like is dead
Thx anyway

**Comment by gabguy** [comment]
Pressing the "Update" button resets the JSON file where the core preferences are saved.
Please fix this

**Comment by mario-64** [comment]
Pretty sure this app has been abandoned.

**Comment by preppietechie** [comment]
> Pretty sure this app has been abandoned.

Eh, people have lives. Things happen. The code is open, so any one of us could fork it and continue the work. I’m using Pocket Sync for now. I don’t like it as much as pocket updater, but it gets the job done.

https://github.com/neil-morrison44/pocket-sync

**Comment by RetroDriven** [comment]
Is this issue still happening with v1.6.1?
