### ISSUE TITLE
Updater stops responding.

### ISSUE THREAD

**Issue by k5jat** [RetroDriven/Pocket_Updater#81]
The Updater, when I went to run it today, stopped responding. It gets just past the section in the screenshot and just stops responding.

![image](https://github.com/RetroDriven/Pocket_Updater/assets/764593/fd128fe9-117c-4101-ac04-2e47e8280036)

I ran the non-gui updater and it works fine, so it's not the DS card.

**Comment by dreimer1986** [comment]
Did you happen to click around in other apps and windows? This happened quite often to me as soon the the updater loses focus as it seems...

**Comment by k5jat** [comment]
> Did you happen to click around in other apps and windows? This happened quite often to me as soon the the updater loses focus as it seems...

It just stops doing anything. I've left it running for 10 minutes without touching it and nothing. Task Manager shows zero activity and clicking in the app causes Windows to figure out it's not responding, so you're right about that.

**Comment by RetroDriven** [comment]
Is this issue still happening with v1.6.1?
