### ISSUE TITLE
Add timestamp to Updater Status

### ISSUE THREAD

**Issue by rodrigorega** [RetroDriven/Pocket_Updater#82]
Is it possible to add timestamp to Updater Status window? I started the updater a few hours ago and the last I see is:

```
Checking Core: jotego.jtvulgus
No releases found. Skipping
Looking for Assets
vulgus.rom: Bad checksum!
Downloading vulgus.rom
Finished downloading vulgus.rom
mach9.rom: Bad checksum!
Downloading mach9.rom
Finished downloading mach9.rom
vulgusj.rom: Bad checksum!
Downloading vulgusj.rom
Finished downloading vulgusj.rom
-------------
```

At this point I don't know if the process is still running, there was an error or the update finished correctly.

**Comment by RetroDriven** [comment]
A Progress Bar has been added to v1.6.1 with some more improvements that should fix issues like this now.
