### ISSUE TITLE
Two instances of Pocket Updater show different Cores in list

### ISSUE THREAD

**Issue by Shoey5** [RetroDriven/Pocket_Updater#83]
Pocket Updater seems to lose cores in the gui. I noticed this when was helping a friend setup his Analogue Pocket. His copy of Pocket Updater displayed CPS1, 1.5, 2 cores and I noticed my instance only displays CPS1 even though 1 and 1.5 are installed on my pocket and the settings.json displays all 3 of them.  Also note the screen shot (both lists sorted by core names) with the top instance that I've been running for a while and the below instance I ran from a different directory. Notice the CPS missing cores

Am I missing something or is this a bug?

![PU1 6 0](https://github.com/RetroDriven/Pocket_Updater/assets/87686055/285e47f2-2f0e-4f5e-b5a3-0d1dfd52b7af)

pocket_updater_settings.json
    "jotego.jtcps1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps15": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },

**Comment by RetroDriven** [comment]
Is this issue still happening with v1.6.1?
