### ISSUE TITLE
Openfpga gba core ，the crt display mode is not supported 

### ISSUE THREAD

**Issue by Bladerunner2024** [RetroDriven/Pocket_Updater#84]
Hello,my analogue pocket os version is v2.1
But i found there was only normal display mode supported when i was playing games on openfpga gba core platform.
I can’t fix it 
Thank u very much if u could do me a favor

**Comment by Dawbo66** [comment]
I don't use this updater as it crashes a lot, but i know that once you've updated you might have to install the filters again, i use pupdate and there's an option for it, that's probably why you've lost the filters.

**Comment by Bladerunner2024** [comment]
> I don't use this updater as it crashes a lot, but i know that once you've updated you might have to install the filters again, i use pupdate and there's an option for it, that's probably why you've lost the filters.

Thanks a lot. I will have a try👍
